name: Metrics
on:
  # Atualiza a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente se quiser atualizar agora
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andre12burger
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          

          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 10
          # Isso diz para não baixar arquivos binários gigantes, o que resolve o bug do 0
          plugin_lines_skipped: |
            *.pth
            *.pt
            *.h5
            *.jpg
            *.png
            *.mp4
            *.zip
