name: Metrics
on:
  # Atualiza a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente se quiser atualizar agora
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andre12burger
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          

          plugin_lines: yes
          plugin_lines_delay: 15
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 10
          # LISTA NEGRA: Coloque aqui o nome exato dos repositórios que são só DATASETS pesados
          # Isso libera o robô para contar o código dos outros projetos sem travar
          plugin_lines_skipped: |
            nome-do-repo-de-imagens
            nome-do-repo-de-pesos
            
          # Opcional: Tenta ignorar arquivos binários automaticamente
          plugin_lines_sections: base
