name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andre12burger
          template: classic
          config_timezone: America/Sao_Paulo
          
          # COMANDO DE LIMPEZA (Com aspas para for√ßar o GitHub a obedecer)
          base: "header, repositories"
          
          # Plugin de Linhas
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 10
          plugin_lines_skipped: |
            *.pth
            *.pt
            *.h5
            *.jpg
            *.png
            *.mp4
            *.zip
            
          # Plugin de Linguagens
          plugin_languages: yes
          plugin_languages_colors: "github"
          plugin_languages_threshold: 1%
