name: Metrics
on:
  # Atualiza a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente se quiser atualizar agora
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: andre12burger
          template: classic
          config_timezone: America/Sao_Paulo
          
          # AQUI ESTÁ O TRUQUE:
          # Removemos 'activity' e 'community'. Deixamos só o cabeçalho e os repositórios (onde estão os dados bons)
          base: header, repositories
          
          # Plugin de Linhas (O seu ponto forte)
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 10
          plugin_lines_skipped: |
            *.pth
            *.pt
            *.h5
            *.jpg
            *.png
            *.mp4
            *.zip
            
          # Plugin de Linguagens (Visual bonito e profissional)
          plugin_languages: yes
          plugin_languages_colors: "github"
          plugin_languages_threshold: 1%
